sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- pypy
before_install:
- wheel version
install:
- pip install -U setuptools wheel pip
- pip install -r tests/requirements.txt
- pip install -e .
- pip install coveralls
script:
- python setup.py test
after_success:
- coveralls
- python setup.py bdist_wheel
- ls -la dist/
- pip install codecov
- codecov
before_deploy:
- python setup.py combine -o dist/portalocker.py
deploy:
  provider: releases
  api_key:
    secure: rqSN1zaF8/9mZYpiU1Em1txC6ZSBG2VjqmeUH7Brp9z0GcIfr8JKoPkIB5W6NyrOPXmBa+eA1nsUsrcDkyMr/q1T5pvJwZl2QtOWayAb0jjvBFv/hDK9VO2eqSADU81YzTWA+U8lRSDSTqmdgWa76LG8Hxc1m76Ns5t2KGxOO5k=
  file: dist/portalocker.py
  skip_cleanup: true
  on:
    repo: WoLpH/portalocker
